- name: Check if Composer is installed.
  stat: "path=/usr/bin/composer"
  register: composer_bin
  tags: composer

- name: get composer installer checksum
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists
  tags: composer

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists
  tags: composer

- name: Run Composer installer.
  command: >
    php composer-setup.php
    chdir=/tmp
  when: not composer_bin.stat.exists
  tags: composer

- name: Move Composer into globally-accessible location.
  command: mv /tmp/composer.phar /usr/local/bin/composer
  when: not composer_bin.stat.exists
  tags: composer

- name: check if symfony app exist
  stat: "path=/vagrant/{{ application_folder }}/composer.json"
  register: symfonyapp
  tags: composer

- name: create new symfony app
  become: no
  command: composer create-project symfony/website-skeleton /vagrant/{{ application_folder}}
  when: not symfonyapp.stat.exists


- name: install dependencies
  composer:
    command: install
    working_dir: /vagrant/{{application_folder}}
  when: symfonyapp.stat.exists